[package]
name = "alloy-generic"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.13", features = ["full", "signer-keystore", "reqwest"] }
serde = { version = "1.0", features = ["derive"] }
